# Generated by Django 4.2.5 on 2023-09-22 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icecream', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='icecream',
            table='flavours',
        ),
    ]
