# Generated by Django 4.2.5 on 2023-10-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecream', '0002_alter_icecream_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobil', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'contact_info',
            },
        ),
        migrations.AlterField(
            model_name='icecream',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
